import React from 'react'

export default function PrivacyPolicyPage() {
    return (
        <>
            <section>
                <h1>AI seznamka Zuzana - Zásady zpracování osobních údajů</h1>
                <p>Používáním seznamky nám dobrovolně udělujete souhlas se zpracováním osobních údajů za účelem zprostředkování online seznamovací služby v takové podobě, jakou na našich webových stránkách popisujeme. Zpracování osobních údajů se řídí těmito zásadami, které si prosím přečtěte. V případě, že se zpracováním osobních údajů nesouhlasíte, nemůžete naši seznamku používat. Pokud je Vám méně než 15 let, seznamku smíte používat pouze v případě, že Váš rodič nebo zákonný zástupce udělí souhlas za Vás. Souhlas nám udělujete na dobu neurčitou, ale můžete ho kdykoli odvolat. Také máte mimo jiné právo na úpravu nebo výmaz osobních údajů ze systému. Pro uplatnění kteréhokoli práva ze zákona č. 110/2019 Sb. o zpracování osobních údajů nás můžete kontaktovat e-mailem na <a href="mailto:aiseznamka@gmail.com">aiseznamka@gmail.com</a>.</p>
                <p>Za účelem správného fungování seznamky zpracováváme Váš e-mail (primární e-mail Vašeho Google účtu, kterým se na seznamku přihlásíte), text Vašeho seznamovacího inzerátu a také text Vašich kontaktních údajů. Po přihlášení na seznamku Vaším Google účtem také chvíli v paměti Vašeho prohlížeče uchováváme token mající přístup k některým údajům z Vašeho Google účtu, ze kterých ale následně používáme a ukládáme do naší databáze pouze již zmíněný primární e-mail, nic jiného.</p>
                <p>E-mailovou adresu propojíme s Vaším seznamovacím inzerátem a bude používána v následujícím rozsahu: 1) Možnost přihlásit se na seznamku stejným e-mailem (respektive stejným Google účtem) opakovaně a zkontrolovat, upravit nebo zadat nový inzerát nebo nové kontaktní informace. 2) Zasílání e-mailů o nalezených potenciálních protějšcích (= match s jiným uživatelem seznamky). 3) Předávání Vaší e-mailové adresy Vašim potenciálním protějškům (ostatním uživatelům seznamky, které seznamka vyhodnotí jako match) jako kontaktní údaj na Vás.</p>
                <p>Text Vašeho seznamovacího inzerátu může mít víceméně libovolnou podobu (pokud splňuje, že se skutečně jedná o seznamovací inzerát, a dodržuje platné zákony ČR) a zpravidla bude obsahovat více osobních údajů o Vás, pokud je do textu umístíte. Text inzerátu je po vytvoření a odeslání uložen a uchováván v naší databázi, propojený s Vaší e-mailovou adresou. K zobrazení úplného textu inzerátu máte přístup pouze Vy a správci databáze seznamky, ale informace z inzerátu se mohou dostat (a zpravidla dostanou) k Vašim potenciálním protějškům. Seznamka nikdy Vašim potenciálním protějškům neukáže úplné znění inzerátu, ale vemte prosím na vědomí, že umělá inteligence může používat všechny údaje z Vašeho inzerátu a vlastními slovy Vašim potenciálním protějškům popisovat vše, co v inzerátu našla. Berte také prosím na vědomí, že seznamka využívá umělé inteligence jazykových modelů GPT-3.5 Turbo a GPT-4 Turbo od společnosti OpenAI, a těmto modelům jsou tedy všechna data z Vašeho inzerátu předávána, aby mohla být zpracována za účelem poskytnutí takové seznamovací služby, kterou na našich webových stránkách popisujeme, přičemž zpracování Vašich dat těmito jazykovými modely se řídí zásadami společnosti OpenAI.</p>
                <p>Text Vašich kontaktních údajů je dobrovolný údaj, který ke svému inzerátu nemusíte zadat, pokud nechcete. Pokud ho zadáte, bude uchováván společně s Vaším inzerátem v databázi naší seznamky. Do textu můžete uvést Vaše kontaktní údaje nad rámec Vaší e-mailové adresy, pokud chcete, aby Vás potenciální protějšky mohly kontaktovat například na Instagramu, Facebooku, apod. Vezměte prosím na vědomí, že cokoli, co do tohoto textu napíšete, bude Vašim potenciálním protějškům, které seznamka najde a vyhodnotí jako match, předáváno jako kontaktní údaje na Vás, a to podobným způsobem, jako jim jsou předávány informace z textu inzerátu (nikoli v úplném znění, ale v takovém, které vytvoří umělá inteligence vlastními slovy). I tento text určený pro ukládání kontaktních údajů bude tedy předáván modelům GPT-3.5 Turbo a GPT-4 Turbo od společnosti OpenAI, aby bylo možné ho nechat zpracovat umělou inteligencí do podoby vhodné pro seznamku, ale také zkontrolovat, zda se vůbec skutečně jedná o kontaktní údaje nebo ne. Máte povoleno uvést pouze své kontaktní údaje nebo kontaktní údaje osoby, která Vám to povolila. Kromě předávání potenciálním protějškům a modelům GPT-3.5 Turbo a GPT-4 Turbo můžete text s kontaktními údaji zobrazit pouze Vy a správci databáze seznamky.</p>
                <p>Po vytvoření a odeslání Vašeho inzerátu jsou všechna data související s ním uchovávána v naší databázi měsíc, a během tohoto měsíce je inzerát opakovaně testován umělou inteligencí seznamky na kompatibilitu s ostatními inzeráty. Testování na kompatibilitu začíná ve chvíli, kdy uběhne 24 hodin od odeslání inzerátu, a od té chvíle je inzerát tzv. aktivní, dokud nevyprší jeho již zmíněná platnost jeden měsíc. Do 24 hodin od odeslání je inzerát tzv. neaktivní a skrz rozhraní naší seznamky je možné ho upravovat, pokud se přihlásíte stejným Google účtem, který jste použili při vytváření a odeslání inzerátu. Aktivní inzerát není možné skrz rozhraní seznamky upravovat, jde ho pouze zobrazit. Pokud si budete přát změnit nebo odstranit jakékoli osobní údaje z Vašeho inzerátu v době, kdy je aktivní, zkontaktujte nás prosím e-mailem na <a href="mailto:aiseznamka@gmail.com">aiseznamka@gmail.com</a>. Po vypršení platnosti inzerát přestane být zahrnován do testování na kompatibilitu s ostatními inzeráty a stává se neplatným. Takový inzerát bude z naší databáze bez zbytečného odkladu smazán, nicméně, vezměte prosím na vědomí, že si z technických důvodů vyhrazujeme právo uchovat v databázi informaci o tom, že se tam Váš inzerát nacházel a kdy vypršela jeho platnost, společně s Vaší e-mailovou adresou, a to na dobu neurčitou. V případě, že budete chtít zažádat o úplný výmaz, můžete tak učinit na našem výše zmíněném e-mailu. Po vypršení platnosti Vašeho inzerátu se můžete rozhodnout vytvořit a odeslat nový inzerát, přičemž zpracování jeho dat se bude řídit stejnými zásadami.</p>
                <p>Společnými správci osobních údajů, které shromažďuje AI seznamka Zuzana, jsou fyzické osoby Ondřej Vitík a Martin Sedmihradský. Hlavní databáze sloužící k ukládání osobních údajů je provozována na serverech společnosti WEDOS Internet, a. s. Z těchto serverů je v pravidelných intervalech odesílána kopie dat na servery společnosti PythonAnywhere LLP, kde jsou data taktéž uchovávána a dále zpracovávána dle těchto zásad (předávání dat umělé inteligenci ke zpracování, odesílání e-mailů).</p>
                <p>Správci osobních údajů se zavazují, že osobní údaje budou použity pouze k těm účelům, které jsou vymezeny těmito zásadami, a že pro osobní údaje zajistí takové maximální zabezpečení, které rozpočet projektu umožňuje. Data jsou mezi servery přeposílána šifrovaně (SSL protokol), všechny přístupy do databází jsou zabezpečeny a chráněny proti neoprávněnému přístupu.</p>
            </section>
        </>
    )
}
